<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zone;

class ZoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Zone::insert([
            ['Nodo' => 'A3', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A7', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A4', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A1', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A8', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AJ', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A5', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'A0', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AP', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Isidro Mendoza', 'Zonal' =>'Arequipa', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AR', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AX', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'CU', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'GA', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'HS', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'CT', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EZ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'DB', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'GY', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'UE', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '6L', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '6K', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'CK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '5N', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '5O', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '5P', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '6I', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'DC', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'FN', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '7I', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => '5M', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EC', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Cuzco', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'EP', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'PR', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EM', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CB', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'LO', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'LS', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EO', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CE', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'AV', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'ES', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'ER', 'Gestor Averias' => 'Torres Pareja Nathaly', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'AN', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CX', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'PP', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'ZP', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'VE', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'DM', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'FM', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'TH', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CM', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'ML', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'MM', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'ZA', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'HN', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'CG', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'MS', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'SJ', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'SR', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'PC', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'PA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'SO', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'PY', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'CN', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'MN', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'RI', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'CA', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'MT', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'SM', 'Gestor Averias' => 'Mondragon Frank', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'AK', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'PT', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Paula Gavidia', 'Zonal' =>'Lima', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'SS', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'T1', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'VL', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'SN', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'HI', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'BA', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'LA', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'CR', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'RO', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'LG', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'SG', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'P1', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'CV', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'MO', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'CQ', 'Gestor Averias' => 'Mendoza Ipanaque Isidro', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'VI', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'SI', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'JU', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'MY', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'LV', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'WA', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'SP', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'LT', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'SB', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'T3', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'VS', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'IC', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'C2', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'CH', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'TB', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'P3', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'VN', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'AG', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'AA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'BE', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'LK', 'Gestor Averias' => 'Isidro Mendoza', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' =>'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => '7M', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => '7L', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EJ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EN', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'JK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'JL', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'PX', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'UP', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EI', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'EL', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'PJ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'QE', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => '6G', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'GR', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'FQ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'GJ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' =>'Puno', 'Supervisor' => 'Quispe Dueñas Armando'],
        ]);
    }
}
