<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zone;

class ZoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Zone::insert([
            ['Nodo' => 'CM', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'HN', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'ML', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'MM', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AK', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AN', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'CX', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'PP', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'PT', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'SS', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'ZP', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'VE', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'FM', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'DM', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EO', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'LS', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'AV', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EP', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'CE', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'ES', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'TH', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'EC', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'T1', 'Gestor Averias' => 'Benites Marcelo Lizeth ', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Fernandez  Cerna  Hector'],
            ['Nodo' => 'ZA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'SN', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'SG', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'ER', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'HI', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'BA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'LA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CR', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'RO', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'LG', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'P1', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CV', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'MO', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CQ', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Barragan Sante Karla', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CB', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'CG', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'MS', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'VN', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'AR', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'AX', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'CU', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'GA', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'DB', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'HS', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'EZ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'GY', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'CT', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'UE', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => '6G', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'JK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => '7L', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'PX', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'YC', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'QE', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Condorhuaman Cconochuillca Zenon'],
            ['Nodo' => 'EI', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'EJ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'EK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'EN', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'JL', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => 'UP', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Puno', 'Supervisor' => 'Machado Benites Jorge '],
            ['Nodo' => '6L', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '6K', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'CK', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '5N', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '5O', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '5P', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '7M', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '6I', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'DC', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'FN', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '7I', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => '5M', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'EL', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'FQ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'PJ', 'Gestor Averias' => 'Soto Castillo Fiorella', 'Gestor Altas' => 'Soto Castillo Fiorella', 'Zonal' => 'Cuzco', 'Supervisor' => 'Marcelo Serquen  Emilio'],
            ['Nodo' => 'LO', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'PR', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'VL', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'EM', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'PA', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'SJ', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'PC', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'SR', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'CN', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'MN', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Cacha Castro Santiago'],
            ['Nodo' => 'PY', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'SO', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'RI', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'LV', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'SB', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'CA', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'MT', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'SM', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'GX', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'WA', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'JU', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'SP', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Rojas Espinoza Christian', 'Zonal' => 'Lima', 'Supervisor' => 'Perez Salom Israel'],
            ['Nodo' => 'AS', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'ZS', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'CL', 'Gestor Averias' => 'Vela Ortega Pamela', 'Gestor Altas' => 'Levano Rios Franck', 'Zonal' => 'Lima', 'Supervisor' => 'Callo Herrera Juan'],
            ['Nodo' => 'AA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'UM', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
            ['Nodo' => 'AA', 'Gestor Averias' => 'Meza Allpas Edwin', 'Gestor Altas' => 'Vilcherres Paucar Rocio', 'Zonal' => 'Lima', 'Supervisor' => 'Quispe Dueñas Armando'],
        ]);
    }
}
